--From the table DEPOSIT perform the following queries:  
--Part – A:  
--1. Copy all records from DEPOSIT where AMOUNT > 3000 into HIGH_AMOUNT.

SELECT * 
INTO HIGH_AMOUNT
FROM DEPOSIT
WHERE AMOUNT > 3000

SELECT * FROM HIGH_AMOUNT

--2. Copy only CNAME and AMOUNT from DEPOSIT where BNAME = 'MAVDI' into MAVDI_CUSTOMERS. 

SELECT CNAME,AMOUNT 
INTO MAVDI_CUSTOMERS
FROM DEPOSIT
WHERE BNAME = 'MAVDI'

SELECT * FROM MAVDI_CUSTOMERS

--3. Copy records of DEPOSIT where ADATE > '2025-01-01' into RECENT_DEPOSITS.  

SELECT *
INTO RECENT_DEPOSITS
FROM DEPOSIT
WHERE ADATE > '2025-01-01'

SELECT * FROM RECENT_DEPOSITS

--4. Copy distinct BNAME from DEPOSIT into BRANCH_LIST.  

SELECT DISTINCT BNAME
INTO BRANCH_LIST
FROM DEPOSIT;

SELECT * FROM BRANCH_LIST;

--5. Copy top 5 records from DEPOSIT into TOP_DEPOSITS.  

SELECT TOP 5 *
INTO TOP_DEPOSITS
FROM DEPOSIT

SELECT * FROM TOP_DEPOSITS

--6. Copy records where AMOUNT between 2000 and 6000 into MID_RANGE.  

SELECT *
INTO MID_RANGE
FROM DEPOSIT
WHERE AMOUNT BETWEEN 2000 AND 6000

SELECT * FROM MID_RANGE

--7. Copy distinct branch names from DEPOSIT into UNIQUE_BRANCH. 

SELECT DISTINCT BNAME
INTO UNIQUE_BRANCH
FROM DEPOSIT

SELECT * FROM UNIQUE_BRANCH

--8. Copy records with NULL branch into NO_BRANCH_ASSIGNED.  

SELECT *
INTO NO_BRANCH_ASSIGNED
FROM DEPOSIT
WHERE BNAME IS NULL

SELECT * FROM NO_BRANCH_ASSIGNED

--9. Copy all records and rename AMOUNT as BALANCE into DEPOSIT_COPY.  

SELECT *
INTO DEPOSIT_COPY
FROM DEPOSIT

SP_RENAME 'DEPOSIT_COPY.AMOUNT','BALANCE'

SELECT * FROM DEPOSIT_COPY

--10. Copy records where BNAME in ('MAVDI','BEDI') into SELECTED_BRANCH.  

SELECT *
INTO SELECTED_BRANCH
FROM DEPOSIT
WHERE BNAME IN('MAVDI','BEDI')

SELECT * FROM SELECTED_BRANCH
 
--From the table Student perform the following queries:  
--Part – B:  
--11. Create a new table STUDENT_BACKUP from STUDENT without copying any data. 

SELECT *
INTO STUDENT_BACKUP
FROM STUDENT
WHERE 1=0

SELECT * FROM STUDENT_BACKUP
--12. Copy SNAME and CITY where BRANCH = 'COMPUTER' into CS_STUDENTS.  

SELECT SNAME,CITY
INTO CS_STUDENTS
FROM STUDENT
WHERE BRANCH = 'COMPUTER'

SELECT * FROM CS_STUDENTS

--13. Copy top 3 students based on SPI into TOPPER_LIST. 

SELECT TOP 3 *
INTO TOPPER_LIST
FROM STUDENT
ORDER BY SPI DESC

SELECT * FROM TOPPER_LIST

--14. Copy distinct CITY from STUDENT into CITY_LIST. 

SELECT DISTINCT CITY 
INTO CITY_LIST
FROM STUDENT

SELECT * FROM CITY_LIST

--15. Copy records where STDID between 103 and 108 into MID_STUDENTS. 

SELECT *
INTO MID_STUDENTS
FROM STUDENT
WHERE STDID BETWEEN 103 AND 108

SELECT * FROM MID_STUDENTS


--From the table Student perform the following queries:  
--Part – C:  
--16. Copy records with NULL branch into NULL_BRANCH_STUDENTS. 

SELECT *
INTO NULL_BRANCH_STUDENTS
FROM STUDENT
WHERE BRANCH IS NULL

SELECT * FROM NULL_BRANCH_STUDENTS

--17. Copy all STUDENT records and rename SPI as PERFORMANCE into STUDENT_COPY. 

SELECT *
INTO STUDENT_COPY
FROM STUDENT

SP_RENAME 'STUDENT_COPY.SPI','PERFORMANCE'

SELECT * FROM STUDENT_COPY

--18. Copy records where CITY in ('RAJKOT','SURAT') into CITY_WISE. 
SELECT *
INTO CITY_WISE
FROM STUDENT
WHERE CITY IN('RAJKOT','SURAT')

SELECT * FROM CITY_WISE

--19. Copy students where BRANCH <> 'CIVIL' into NON_CIVIL_STUDENTS.  

SELECT *
INTO NON_CIVIL_STUDENTS
FROM STUDENT
WHERE BRANCH <> 'CIVIL'

SELECT * FROM NON_CIVIL_STUDENTS

--20. Copy selected columns (SNAME, CITY) from STUDENT table into a new table. 

SELECT SNAME,CITY
INTO NEW_TABLE
FROM STUDENT

SELECT * FROM NEW_TABLE

--EXTRA

--1. Copy top 5 records where AMOUNT < 1000 into LOW_DEPOSIT.

SELECT TOP 5 *
INTO LOW_DEPOSIT
FROM DEPOSIT
WHERE AMOUNT < 1000 

SELECT * FROM LOW_DEPOSIT

--2. Copy records where AMOUNT >= 5000 into HIGH_DEPOSIT.  

SELECT *
INTO HIGH_DEPOSIT
FROM DEPOSIT
WHERE AMOUNT >= 5000 

SELECT * FROM HIGH_DEPOSIT

--3. Copy only ACTNO and CNAME from DEPOSIT into CUSTOMER_DETAILS.  

SELECT ACTNO,CNAME
INTO CUSTOMER_DETAILS
FROM DEPOSIT 

SELECT * FROM CUSTOMER_DETAILS


--4. Copy records where BNAME = 'BEDI' into BEDI_CUSTOMERS. 

SELECT *
INTO BEDI_CUSTOMERS
FROM DEPOSIT 
WHERE BNAME = 'BEDI'

SELECT * FROM BEDI_CUSTOMERS

--5. Copy records where BNAME = 'AJI' into AJI_DEPOSITS.  

SELECT *
INTO AJI_DEPOSITS
FROM DEPOSIT 
WHERE BNAME = 'AJI'

SELECT * FROM AJI_DEPOSITS

--6. Copy records where AMOUNT is between 1000 and 4000 into NORMAL_DEPOSITS.  

SELECT *
INTO NORMAL_DEPOSITS
FROM DEPOSIT 
WHERE AMOUNT BETWEEN 1000 AND 4000

SELECT * FROM NORMAL_DEPOSITS


--7. Copy records where ADATE < '2025-01-01' into OLD_DEPOSITS. 

SELECT *
INTO OLD_DEPOSITS
FROM DEPOSIT 
WHERE ADATE < '2025-01-01'

SELECT * FROM OLD_DEPOSITS

--8. Copy records where BNAME is not equal to 'BEDI' into OTHER_BRANCH_DEPOSITS.

SELECT *
INTO OTHER_BRANCH_DEPOSITS
FROM DEPOSIT 
WHERE BNAME <> 'BEDI'

SELECT * FROM OTHER_BRANCH_DEPOSITS

--9. Copy top 3 records with only CNAME and BNAME from DEPOSIT into 
--CUSTOMER_BRANCH.  


SELECT TOP 3 CNAME,BNAME
INTO CUSTOMER_BRANCH
FROM DEPOSIT 

SELECT * FROM CUSTOMER_BRANCH

--10. Create a table DEPOSIT_EMPTY with the same structure as DEPOSIT but no records. 


SELECT *
INTO DEPOSIT_EMPTY
FROM DEPOSIT 
WHERE 1=0

SELECT * FROM DEPOSIT_EMPTY

--11. Copy only ACTNO, AMOUNT, and ADATE into TRANSACTION_INFO. 

SELECT ACTNO,AMOUNT,ADATE
INTO TRANSACTION_INFO
FROM DEPOSIT 

SELECT * FROM TRANSACTION_INFO

--12. Copy records where AMOUNT = 3000 into EXACT_3000. 


SELECT *
INTO EXACT_3000
FROM DEPOSIT 
WHERE AMOUNT = 3000

SELECT * FROM EXACT_3000
